version: '3.7'

services:
  employeemanagement-db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - '53535:1433'
    environment:
      - DB_USER=SA
      - SA_PASSWORD=#localDockerPassword#
      - DB_CONTAINER_NAME=dev_employeemanagement
      - ACCEPT_EULA=Y
    volumes:
      - employeemanagement-data:/var/lib/sqlserver/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "53542:5775/udp"
      - "53541:6831/udp"
      - "53543:6832/udp"
      - "53544:5778"
      - "53545:16686"
      - "53546:14250"
      - "53547:14268"
      - "53548:14269"
      - "53549:9411"

        
volumes:
  # compose volumes marker - do not delete
  employeemanagement-data:
